// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASxViW-kqySm6uZRUPI1iIDDeDDoq_BSI',
    appId: '1:378978387373:web:0c1aece5226ccd8d4f8d24',
    messagingSenderId: '378978387373',
    projectId: 'talks-8a22f',
    authDomain: 'talks-8a22f.firebaseapp.com',
    storageBucket: 'talks-8a22f.firebasestorage.app',
    measurementId: 'G-QLE0NSH4DY',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASxViW-kqySm6uZRUPI1iIDDeDDoq_BSI',
    appId: '1:378978387373:web:ec373571c5e2f3f74f8d24',
    messagingSenderId: '378978387373',
    projectId: 'talks-8a22f',
    authDomain: 'talks-8a22f.firebaseapp.com',
    storageBucket: 'talks-8a22f.firebasestorage.app',
    measurementId: 'G-F2BYPJG4FS',
  );

}